[package]
name = "tester"
version = "0.1.0"
edition = "2021"

[dependencies]
parser = { path = "../parser" }
mimalloc-rust = "0.2.0"
bstr = "1.1.0"
tracing = "0.1.35"
tracing-subscriber = "0.3.11"
walkdir = "2.3.2"
anyhow = "1.0.58"

