[package]
name = "parser"
version = "0.1.0"
edition = "2021"

[dependencies]
enum-map = "2.1.0"
tinyvec = { version = "1.6.0", features = [] }
fast-float = "0.2.0"
memchr = "2.5.0"
bstr = "1.1.0"
tracing = "0.1.35"