[package]
name = "parser"
version = "0.1.0"
edition = "2021"
rust-version = "1.71.0"

[dependencies]
enum-map = "2.7.3"
tinyvec = { version = "1.8.1", features = [] }
fast-float = "0.2.0"
memchr = "2.7.4"
bstr = "1.11.1"
tracing = "0.1.41"

[lints]
workspace = true